# Generated by Django 5.0.7 on 2024-07-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=55)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='blog/img/')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('draft', models.BooleanField(default=True)),
                ('time_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
